### ISSUE TITLE
metrics that are 0 not being printed?

### ISSUE THREAD

**Issue by hpiwowar** [figshare/Total-Impact#11] opened 2011-05-16 14:42 UTC
I think maybe metrics aren't printed when their value is zero.  See for example a Dryad dataset with 0 downloads, like 10.5061/dryad.8602 (http://datadryad.org/handle/10255/dryad.1544).  Maybe we need to do a better job between distinguishing between 0s and Nones at some layer?

**Comment by jasonpriem** [comment] 2011-05-16 15:25
I think that's a feature, not a bug. Let's say you upload 200 datasets 
from stuff you've funded. You don't want to have to wade through all of 
them looking for a number. You just want to see the ones where there's 
something _to_ see--a number other than zero.

**Comment by hpiwowar** [comment] 2011-05-16 15:29
Hmmm, I think I disagree.  It conveys information to know that something has
been cited zero times (as opposed to an unmeasured or unmeasureable number
of times).  I think it undermines our evenhandedness to hide zeros.

If we do hide zeros, I think that needs to be very clear at the top of the
page.

h

**Comment by hpiwowar** [comment] 2011-05-16 15:29
Hmmm, I think I disagree.  It conveys information to know that something has been cited zero times (as opposed to an unmeasured or unmeasureable number of times).  I think it undermines our evenhandedness to hide zeros.

If we do hide zeros, I think that needs to be very clear at the top of the page.

**Comment by jasonpriem** [comment] 2011-05-16 15:31
I'll buy that. We should print zeroes. Then there should be a UI control 
to hide them, if the user wants.
j

**Comment by jasonpriem** [comment] 2011-05-27 23:06
Closing this issue, which is now addressed by #12, "Python plugins: return array of event objects"

**Closed as completed by jasonpriem** 2011-05-27 23:06 UTC
